version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      HOSTNAME: 10.0.16.14
      # Uncomment the following line to disable telemetry during runtime
      # NEXT_TELEMETRY_DISABLED: 1
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always
