# Use an official Node.js runtime as a parent image
FROM node:20.11-alpine3.19 AS base

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

