# Use an official Node.js runtime as a parent image
FROM node:20.11-alpine3.19 AS base

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application code
# COPY . .

# Build the Next.js application
# RUN yarn build

# This stage will be pushed to a public repository
